package dev.otherworld.budget.data.remote

import dev.otherworld.budget.domain.model.Account
import dev.otherworld.budget.domain.model.BudgetStatus
import dev.otherworld.budget.domain.model.Category
import dev.otherworld.budget.domain.model.DraftTransaction
import dev.otherworld.budget.domain.model.Money
import dev.otherworld.budget.domain.model.RecentTransaction
import dev.otherworld.budget.domain.model.SplitLine
import dev.otherworld.budget.domain.model.SplitPart
import dev.otherworld.budget.domain.model.UpcomingBill
import java.io.File
import java.time.LocalDate

data class Capabilities(
    val ocrAvailable: Boolean,
    val currency: String,
    val version: String,
    val splitsAvailable: Boolean,
    // Absent (false) on an older server: the check side (balances, budget, bills) isn't
    // available there, and the Overview tab shows its "update your server" state instead.
    val checkAvailable: Boolean = false,
)

/**
 * The outcome of a successful [BudgetApi.createTransaction]: the new transaction's [id], plus
 * [splitsError] -- the server's message when the transaction was recorded but its per-item splits
 * were rejected (e.g. the split amounts did not sum to the total). The transaction still exists, so
 * this is a success carrying a caveat, not a failure. Null when there was no split problem -- which,
 * until splits are actually sent, is always. A replay of an already-seen idempotency key never
 * re-reports a split error.
 *
 * [categoryError] is the same kind of caveat for the category: the account's owner can't use the
 * one chosen (one of the caller's own, on someone else's shared account), so the server recorded
 * the transaction without it. Null otherwise, and on an older server, which refused the post.
 */
data class CreatedTransaction(val id: Long, val splitsError: String?, val categoryError: String? = null)

data class CreateTransactionRequest(
    val accountId: Long,
    val categoryId: Long?,
    val date: LocalDate,
    val merchant: String,
    val total: Money,
    /**
     * Null for a Quick Add manual entry, where there is no receipt to attach. The server contract
     * makes `photo` optional on `POST transactions` for exactly this reason
     * (`docs/server-api-contract.md`), and [BudgetApi.createTransaction] must then omit the part
     * entirely rather than send an empty one.
     */
    val photo: File?,
    /**
     * The per-item category allocations for a split save; null (the default) for an ordinary,
     * single-category transaction. [BudgetApi.createTransaction] must then omit the `splits` part
     * entirely rather than send an empty array, exactly like [photo].
     */
    val splits: List<SplitPart>? = null,
)

/**
 * The single seam between the app and the user's Nextcloud.
 * Implementations must not throw; every failure arrives as a [BudgetApiError]
 * inside a failed [Result].
 */
interface BudgetApi {
    suspend fun capabilities(): Result<Capabilities>
    suspend fun accounts(): Result<List<Account>>
    suspend fun categories(): Result<List<Category>>
    suspend fun recentTransactions(limit: Int = 50): Result<List<RecentTransaction>>
    suspend fun extract(photo: File): Result<DraftTransaction>
    /**
     * Posts one transaction, tagged with [idempotencyKey] so the server dedupes a replay of the
     * same request instead of creating a second transaction. The key is a per-queue-row UUID
     * (`docs/server-api-contract.md`), stable across every retry of that row and generated by
     * [dev.otherworld.budget.data.repo.ReceiptRepository]; callers never invent one here. Max 64
     * characters -- a UUID is 36 -- or the server answers 400.
     */
    suspend fun createTransaction(request: CreateTransactionRequest, idempotencyKey: String): Result<CreatedTransaction>

    /** `month` null lets the server pick the user's current budget month (spec §1.2). */
    suspend fun budgetStatus(month: String? = null): Result<BudgetStatus>

    /** [days] defaults to 14, matching the server's own default and clamp (spec §1.3). */
    suspend fun upcomingBills(days: Int = 14): Result<List<UpcomingBill>>

    /** The per-item parts of one transaction (spec §1.1), for a row whose `is_split` is true. */
    suspend fun transactionSplits(id: Long): Result<List<SplitLine>>
}
